### ISSUE TITLE
Log preview keeps shuting down before the pipeline completes

### ISSUE THREAD

**Issue by frousseu** [GEO-BON/biab-2.0#78]
When running a pipeline (e.g. SDM), the logs of intermediates steps (seeable through the + sign) keep shuting down after opening until the pipelone is completed. This is with Firefox or Chrome on Windows. I don't think it was doing that until the appearence of the @nodeno in the pipeline UI.

**Comment by jmlord** [comment]
Yes, I just saw that too, thanks for putting in the issue. Should be fixed soon.
